# coding=utf-8

from unittest2 import TestCase
from syntaxnet_wrapper.utils.pos_aggregation import pos_aggregate

class TestPostAggregation(TestCase):

    def test_pos_aggregate(self):
        test_values = [
            ([{u'1': {u'index': 1, u'token': u'il', u'pos': u'_',
                             u'feats': u'Gender=Masc|Number=Sing|Person=3|PronType=Prs|fPOS=PRON++',
                             u'label': u'PRON'},
                      u'3': {u'index': 3, u'token': u'et', u'pos': u'_', u'feats': u'fPOS=CONJ++',
                             u'label': u'CONJ'},
                      u'2': {u'index': 2, u'token': u's\u2019arr\xeata', u'pos': u'_',
                             u'feats': u'Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|fPOS=VERB++',
                             u'label': u'VERB'}, u'5': {u'index': 5, u'token': u'sa', u'pos': u'_',
                                                        u'feats': u'Gender=Fem|Number=Sing|fPOS=DET++',
                                                        u'label': u'PRON'},
                      u'4': {u'index': 4, u'token': u'sortit', u'pos': u'_',
                             u'feats': u'Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|fPOS=VERB++',
                             u'label': u'VERB'},
                      u'7': {u'index': 7, u'token': u'de', u'pos': u'_', u'feats': u'fPOS=ADP++',
                             u'label': u'ADP'}, u'6': {u'index': 6, u'token': u'montre', u'pos': u'_',
                                                       u'feats': u'Gender=Fem|Number=Sing|fPOS=NOUN++',
                                                       u'label': u'VERB'},
                      u'9': {u'index': 9, u'token': u'poche.', u'pos': u'_',
                             u'feats': u'Gender=Fem|Number=Sing|fPOS=NOUN++', u'label': u'NOUN'},
                      u'8': {u'index': 8, u'token': u'sa', u'pos': u'_',
                             u'feats': u'Gender=Fem|Number=Sing|fPOS=DET++', u'label': u'DET'}}],
             {'animacy': {'inan': 0, 'hum': 0, 'nhum': 0, 'anim': 0},
              'verbform': {'ger': 0, 'conv': 0, 'gdv': 0, 'vnoun': 0, 'part': 0, 'sup': 0, 'inf': 0, 'fin': 2},
              'number': {'count': 0, 'tri': 0, 'grpl': 0, 'inv': 0, 'ptan': 0, 'coll': 0, 'pauc': 0, 'dual': 0,
                         'sing': 7, 'grpa': 0, 'plur': 0},
              'aspect': {'perf': 0, 'hab': 0, 'prosp': 0, 'iter': 0, 'imp': 0, 'prog': 0},
              'polarity': {'neg': 0, 'pos': 0},
              'ratio': {'ratio_adj_propn': 0, 'ratio_adv_propn': 0, 'ratio_adj_verb': 0.0, 'ratio_adj_pron': 0.0,
                        'ratio_adj_adv': 0, 'ratio_adv_pron': 0.0, 'ratio_adv_det': 0.0, 'ratio_propn_verb': 0.0,
                        'ratio_propn_det': 0.0},
              'mood': {'opt': 0, 'qot': 0, 'sub': 0, 'jus': 0, 'pot': 0, 'des': 0, 'nec': 0, 'imp': 0, 'cnd': 0,
                       'prp': 0, 'ind': 2, 'adm': 0}, 'definite': {'ind': 0, 'cons': 0, 'com': 0, 'spec': 0, 'def': 0},
              'numtype': {'frac': 0, 'range': 0, 'card': 0, 'sets': 0, 'dist': 0, 'ord': 0, 'mult': 0}, 'reflex': 0,
              'degree': {'abs': 0, 'equ': 0, 'pos': 0, 'sup': 0, 'cmp': 0},
              'polite': {'humb': 0, 'infm': 0, 'form': 0, 'elev': 0},
              'upos': {'adv': 0, 'verb': 3, 'noun': 1, 'adp': 1, 'punct': 0, 'sconj': 0, 'propn': 0, 'det': 1, 'sym': 0,
                       'intj': 0, 'pron': 2, 'num': 0, 'x': 0, 'cconj': 0, 'aux': 0, 'part': 0, 'adj': 0},
              'tense': {'past': 2, 'imp': 0, 'fut': 0, 'pqp': 0, 'pres': 0}, 'abbr': 0, 'poss': 0,
              'prontype': {'art': 0, 'exc': 0, 'int': 0, 'neg': 0, 'rcp': 0, 'tot': 0, 'rel': 0, 'dem': 0, 'prs': 1,
                           'ind': 0, 'emp': 0}, 'evident': {'fh': 0, 'nfh': 0},
              'gender': {'neut': 0, 'masc': 1, 'fem': 4, 'com': 0}, 'foreign': 0,
              'person': {'1': 0, '0': 0, '3': 3, '2': 0, '4': 0},
              'voice': {'antip': 0, 'inv': 0, 'pass': 0, 'rcp': 0, 'mid': 0, 'cau': 0, 'act': 0, 'dir': 0}}
             ),
            (
                [{u'1': {u'index': 1, u'token': u'il', u'pos': u'_', u'feats': u'reflex', u'label': u'PRON'}}],
                {'animacy': {'inan': 0, 'hum': 0, 'nhum': 0, 'anim': 0},
                 'verbform': {'ger': 0, 'conv': 0, 'gdv': 0, 'vnoun': 0, 'part': 0, 'sup': 0, 'inf': 0, 'fin': 0},
                 'number': {'count': 0, 'tri': 0, 'grpl': 0, 'inv': 0, 'ptan': 0, 'coll': 0, 'pauc': 0, 'dual': 0,
                            'sing': 0, 'grpa': 0, 'plur': 0},
                 'aspect': {'perf': 0, 'hab': 0, 'prosp': 0, 'iter': 0, 'imp': 0, 'prog': 0},
                 'polarity': {'neg': 0, 'pos': 0},
                 'ratio': {'ratio_adj_propn': 0, 'ratio_adv_propn': 0, 'ratio_adj_verb': 0, 'ratio_adj_pron': 0.0,
                           'ratio_adj_adv': 0, 'ratio_adv_pron': 0.0, 'ratio_adv_det': 0, 'ratio_propn_verb': 0,
                           'ratio_propn_det': 0},
                 'mood': {'opt': 0, 'qot': 0, 'sub': 0, 'jus': 0, 'pot': 0, 'des': 0, 'nec': 0, 'imp': 0, 'cnd': 0,
                          'prp': 0, 'ind': 0, 'adm': 0},
                 'definite': {'ind': 0, 'cons': 0, 'com': 0, 'spec': 0, 'def': 0},
                 'numtype': {'frac': 0, 'range': 0, 'card': 0, 'sets': 0, 'dist': 0, 'ord': 0, 'mult': 0}, 'reflex': 1,
                 'degree': {'abs': 0, 'equ': 0, 'pos': 0, 'sup': 0, 'cmp': 0},
                 'polite': {'humb': 0, 'infm': 0, 'form': 0, 'elev': 0},
                 'upos': {'adv': 0, 'verb': 0, 'noun': 0, 'adp': 0, 'punct': 0, 'sconj': 0, 'propn': 0, 'det': 0,
                          'sym': 0, 'intj': 0, 'pron': 1, 'num': 0, 'x': 0, 'cconj': 0, 'aux': 0, 'part': 0, 'adj': 0},
                 'tense': {'past': 0, 'imp': 0, 'fut': 0, 'pqp': 0, 'pres': 0}, 'abbr': 0, 'poss': 0,
                 'prontype': {'art': 0, 'exc': 0, 'int': 0, 'neg': 0, 'rcp': 0, 'tot': 0, 'rel': 0, 'dem': 0, 'prs': 0,
                              'ind': 0, 'emp': 0}, 'evident': {'fh': 0, 'nfh': 0},
                 'gender': {'neut': 0, 'masc': 0, 'fem': 0, 'com': 0}, 'foreign': 0,
                 'person': {'1': 0, '0': 0, '3': 0, '2': 0, '4': 0},
                 'voice': {'antip': 0, 'inv': 0, 'pass': 0, 'rcp': 0, 'mid': 0, 'cau': 0, 'act': 0, 'dir': 0}}
            ),
            ([{u'1': {u'index': 1, u'token': u'il', u'pos': u'_', u'feats': u'_', u'label': u'PRON'}}],
             {'animacy': {'inan': 0, 'hum': 0, 'nhum': 0, 'anim': 0},
              'verbform': {'ger': 0, 'conv': 0, 'gdv': 0, 'vnoun': 0, 'part': 0, 'sup': 0, 'inf': 0, 'fin': 0},
              'number': {'count': 0, 'tri': 0, 'grpl': 0, 'inv': 0, 'ptan': 0, 'coll': 0, 'pauc': 0, 'dual': 0,
                         'sing': 0, 'grpa': 0, 'plur': 0},
              'aspect': {'perf': 0, 'hab': 0, 'prosp': 0, 'iter': 0, 'imp': 0, 'prog': 0},
              'polarity': {'neg': 0, 'pos': 0},
              'ratio': {'ratio_adj_propn': 0, 'ratio_adv_propn': 0, 'ratio_adj_verb': 0, 'ratio_adj_pron': 0.0,
                        'ratio_adj_adv': 0, 'ratio_adv_pron': 0.0, 'ratio_adv_det': 0, 'ratio_propn_verb': 0,
                        'ratio_propn_det': 0},
              'mood': {'opt': 0, 'qot': 0, 'sub': 0, 'jus': 0, 'pot': 0, 'des': 0, 'nec': 0, 'imp': 0, 'cnd': 0,
                       'prp': 0, 'ind': 0, 'adm': 0}, 'definite': {'ind': 0, 'cons': 0, 'com': 0, 'spec': 0, 'def': 0},
              'numtype': {'frac': 0, 'range': 0, 'card': 0, 'sets': 0, 'dist': 0, 'ord': 0, 'mult': 0}, 'reflex': 0,
              'degree': {'abs': 0, 'equ': 0, 'pos': 0, 'sup': 0, 'cmp': 0},
              'polite': {'humb': 0, 'infm': 0, 'form': 0, 'elev': 0},
              'upos': {'adv': 0, 'verb': 0, 'noun': 0, 'adp': 0, 'punct': 0, 'sconj': 0, 'propn': 0, 'det': 0, 'sym': 0,
                       'intj': 0, 'pron': 1, 'num': 0, 'x': 0, 'cconj': 0, 'aux': 0, 'part': 0, 'adj': 0},
              'tense': {'past': 0, 'imp': 0, 'fut': 0, 'pqp': 0, 'pres': 0}, 'abbr': 0, 'poss': 0,
              'prontype': {'art': 0, 'exc': 0, 'int': 0, 'neg': 0, 'rcp': 0, 'tot': 0, 'rel': 0, 'dem': 0, 'prs': 0,
                           'ind': 0, 'emp': 0}, 'evident': {'fh': 0, 'nfh': 0},
              'gender': {'neut': 0, 'masc': 0, 'fem': 0, 'com': 0}, 'foreign': 0,
              'person': {'1': 0, '0': 0, '3': 0, '2': 0, '4': 0},
              'voice': {'antip': 0, 'inv': 0, 'pass': 0, 'rcp': 0, 'mid': 0, 'cau': 0, 'act': 0, 'dir': 0}})
        ]

        for input_test, result in test_values:
            self.assertDictEqual(result, pos_aggregate(input_test))

